# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Fin_ML',
                'doc_host': 'https://cpeng78.github.io',
                'git_url': 'https://github.com/cpeng78/Fin_ML',
                'lib_path': 'Fin_ML'},
  'syms': {'Fin_ML.core': {'Fin_ML.core.foo': ('core.html#foo', 'Fin_ML/core.py')}}}
