# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Fin_ML',
                'doc_host': 'https://cpeng78.github.io',
                'git_url': 'https://github.com/cpeng78/Fin_ML',
                'lib_path': 'Fin_ML'},
  'syms': { 'Fin_ML.data': { 'Fin_ML.data.get_cv_data': ('data.html#get_cv_data', 'Fin_ML/data.py'),
                             'Fin_ML.data.get_cv_data_df': ('data.html#get_cv_data_df', 'Fin_ML/data.py'),
                             'Fin_ML.data.get_cv_token': ('data.html#get_cv_token', 'Fin_ML/data.py')},
            'Fin_ML.plot': {'Fin_ML.plot.abc': ('plot.html#abc', 'Fin_ML/plot.py')}}}
