# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_plot.ipynb.

# %% auto 0
__all__ = ['abc']

# %% ../nbs/01_plot.ipynb 3
def abc(a, # a number
        b=2, # a number
        ):
    
    "ssdkjfksdjfksdf"

    return a+b
